select * from ACCOUNTS; 
INSERT INTO ACCOUNTS(USERNAME,PASSWORD,EMAIL,CREATED_ON) VALUES ('shiva', 'shiva123','shiva@gmail.com',CURRENT_TIMESTAMP) RETURNING EMAIL;
SELECT * FROM ACCOUNTS WHERE email='sanju1237@gmail.com';   
SET datestyle = default;


CREATE DATABASE "ACCOUNTS_DB"
    WITH OWNER "postgres"
    ENCODING 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TEMPLATE template0;
    

CREATE TABLE  ACCOUNT_DB.ACCOUNTS (`USER_ID` int(11) NOT NULL AUTO_INCREMENT,`USERNAME` varchar(50) NOT NULL,`PASSWORD`varchar(255),`EMAIL` varchar(100) NOT NULL unique,PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8MB4;




CREATE TABLE ACCOUNTS (
	USER_ID serial PRIMARY KEY,
	USERNAME VARCHAR (10) NOT NULL,
	PASSWORD VARCHAR (25 NOT NULL,
	EMAIL VARCHAR (15) UNIQUE NOT NULL,
	CREATED_ON TIMESTAMP 
);


CREATE TABLE ACCOUNTS (
	USER_ID serial PRIMARY KEY,
	USERNAME TEXT NOT NULL,
	PASSWORD TEXT NOT NULL,
	EMAIL TEXT  UNIQUE NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL
);

show datestyle;

SET DATESTYLE TO SQL;
select CURRENT_TIMESTAMP;

INSERT INTO ACCOUNTS(USERNAME,PASSWORD,EMAIL,CREATED_ON) VALUES ('user7', 'pass123','user7@example.com',CURRENT_TIMESTAMP);
INSERT INTO ACCOUNTS(USERNAME,PASSWORD,EMAIL,CREATED_ON) VALUES ('sann', 'sann123','sann65@gmail.com',NOW()) RETURNING user_id;

select * from ACCOUNTS;
delete from ACCOUNTS where USERNAME='user7';
drop table accounts;

SHOW ACCOUNTS;
